### ISSUE TITLE
GPU memory issue 

### ISSUE THREAD

**Issue by shixiao9941** [EagleW/Stage-wise-Fine-tuning#2]
Hi Qingyun, it is really a nice job. Thank you so much for providing the codes and models. When I was try to decode your model, even with batch size 1, my machine suffers from the "CUDA out of memory" problem. I am not sure whether it is because of me or it is because of my machine. I am using V100 GPU with 32GB memory. May I ask what the GPU memory of your machine is when you finetuning and decoding the T5-large model?  Hope to hear from you. Thank you so much!

**Comment by EagleW** [comment]
Hi @shixiao9941 , thank you very much for your interest in our research. Could you share more details and the training bash script you use? Do you use the recommend transformer version? Thank you!

**Comment by shixiao9941** [comment]
Hi Qingyun,

I am really really sorry for the late reply. The email went to spam somehow and I didn't see the issue on Github so I was even doubtful whether I had made the comment on Github. I just found the email yesterday and redid the experiment.  I figured out the reason that I got the issue because there were lots of sleeping processes on our server by other folks that cost the GPU memory. Your T5- large model can run on V100 GPUs. Thank you so much for your reply and help. And very sorry for the late reply.

Best,
Xiao



________________________________

**Comment by EagleW** [comment]
Great! Have a good day!
